version: "3.8"
services:
  app:
    build:
      args:
        user: dime
        uid: 1000
      context: ./
      dockerfile: docker/docker-compose/php/php.dockerfile
    image: php81
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/docker-compose/php/.bashrc:/home/dime/.bashrc
    ports:
      - "8888:8888"
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dev
    links:
      - app

  db:
    image: mysql:latest
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - /home/${USER}/mysqldb:/var/lib/mysql
    networks:
      - dev

networks:
  dev:
    driver: bridge
